import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useStore } from '../../lib/store';
export const RyPositions = () => {
    const portfolio = useStore((s) => s.portfolio);
    const [expandedId, setExpandedId] = useState(null);
    const positions = portfolio.positions || [];
    return (_jsxs("div", { className: "space-y-4", role: "region", "aria-label": "Open positions", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Open Positions" }), _jsxs("div", { className: "text-sm text-slate-400", children: [positions.length, " position", positions.length !== 1 ? 's' : ''] })] }), _jsx("div", { role: "list", className: "space-y-3", children: positions.map((position) => {
                    const isExpanded = expandedId === position.id;
                    const pnlPercent = (position.pnl / position.entryValue) * 100;
                    const isGain = position.pnl >= 0;
                    return (_jsxs("div", { role: "listitem", className: "bg-slate-800 rounded-lg border border-slate-700 overflow-hidden", children: [_jsxs("button", { onClick: () => setExpandedId(isExpanded ? null : position.id), className: "w-full p-4 flex items-center justify-between hover:bg-slate-750 transition-colors text-left", "aria-expanded": isExpanded, "aria-controls": `position-${position.id}`, children: [_jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-mono font-semibold text-white", children: position.symbol }), _jsxs("p", { className: "text-sm text-slate-400", children: [position.type === 'long' ? '📈 Long' : '📉 Short', " \u00B7", ' ', (position.size * position.price).toFixed(0), " size"] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: `text-lg font-semibold ${isGain ? 'text-green-400' : 'text-red-400'}`, children: [isGain ? '+' : '', "$", position.pnl.toFixed(2)] }), _jsxs("div", { className: `text-sm font-mono ${isGain ? 'text-green-400' : 'text-red-400'}`, children: [isGain ? '+' : '', pnlPercent.toFixed(2), "%"] })] })] }), isExpanded && (_jsxs("div", { id: `position-${position.id}`, className: "border-t border-slate-700 p-4 bg-slate-750 space-y-3 text-sm", children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-slate-400", children: "Entry Price" }), _jsxs("p", { className: "font-mono font-semibold", children: ["$", position.entryPrice.toFixed(4)] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-slate-400", children: "Current Price" }), _jsxs("p", { className: "font-mono font-semibold", children: ["$", position.price.toFixed(4)] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-slate-400", children: "Entry Value" }), _jsxs("p", { className: "font-mono font-semibold", children: ["$", position.entryValue.toFixed(2)] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-slate-400", children: "Current Value" }), _jsxs("p", { className: "font-mono font-semibold", children: ["$", (position.size * position.price).toFixed(2)] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-slate-400", children: "Leverage" }), _jsxs("p", { className: "font-mono font-semibold", children: [position.leverage, "x"] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-slate-400", children: "Opened" }), _jsx("p", { className: "font-mono font-semibold", children: new Date(position.openedAt).toLocaleDateString() })] })] }), _jsx("button", { className: "w-full mt-4 bg-red-600 hover:bg-red-700 text-white font-semibold py-2 rounded transition-colors", children: "Close Position" })] }))] }, position.id));
                }) }), (!positions || positions.length === 0) && (_jsx("div", { className: "text-center py-8 text-slate-400", children: "No open positions" }))] }));
};
