import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useFetchQ } from '../hooks/useFetch';
import { useStore } from '../lib/store';
import Card from '../components/Card';
export default function Q() {
    const { loading } = useFetchQ();
    const { safety, ai } = useStore();
    if (loading)
        return _jsx("div", { className: "text-center py-4", children: "Loading Q-Agent..." });
    return (_jsxs("div", { className: "p-8", children: [_jsx("h1", { className: "text-3xl font-bold mb-8", children: "Q-Agent Assistant" }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsx(Card, { children: _jsxs("div", { className: "p-6", children: [_jsx("h2", { className: "text-xl font-semibold mb-4", children: "Status" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-dark-text/70 text-sm mb-1", children: "Agent Status" }), _jsx("p", { className: `text-2xl font-bold ${ai.ctx === 'Ready' ? 'text-green-400' : 'text-yellow-400'}`, children: ai.ctx })] }), _jsxs("div", { children: [_jsx("p", { className: "text-dark-text/70 text-sm mb-1", children: "Mode" }), _jsx("p", { className: `text-lg font-semibold ${safety.deploy ? 'text-green-400' : 'text-orange-400'}`, children: safety.deploy ? 'Trading' : 'Suggest-Only' })] })] })] }) }), _jsx("div", { className: "lg:col-span-2", children: _jsx(Card, { children: _jsxs("div", { className: "p-6", children: [_jsx("h2", { className: "text-xl font-semibold mb-4", children: "Suggestions" }), ai.suggestions && ai.suggestions.length > 0 ? (_jsx("div", { className: "space-y-3", children: ai.suggestions.map((suggestion) => (_jsxs("div", { className: "p-4 rounded border border-dark-border bg-dark-bg", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("p", { className: "font-semibold text-sm", children: suggestion.text }), _jsxs("span", { className: `text-xs px-2 py-1 rounded font-semibold ${suggestion.confidence > 0.7 ? 'bg-green-400/20 text-green-400' : 'bg-yellow-400/20 text-yellow-400'}`, children: [(suggestion.confidence * 100).toFixed(0), "%"] })] }), _jsx("div", { className: "w-full bg-dark-bg rounded-full h-1", children: _jsx("div", { className: "bg-accent h-1 rounded-full transition", style: { width: `${suggestion.confidence * 100}%` } }) })] }, suggestion.id))) })) : (_jsx("p", { className: "text-dark-text/70 text-sm", children: "No suggestions available" }))] }) }) })] }), !safety.deploy && (_jsx(Card, { children: _jsx("div", { className: "p-4 text-center text-orange-400 mt-6", children: "Sandbox Mode: Suggestions Only (No Execution)" }) }))] }));
}
