import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useStore } from '../../lib/store';
import Card from '../Card';
export const RyGreeksMini = () => {
    const { perps } = useStore();
    if (!perps.greeks || perps.greeks.length === 0) {
        return null;
    }
    return (_jsx(Card, { children: _jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "text-sm font-semibold mb-3", children: "Greeks Snapshot" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-xs", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-dark-border", children: [_jsx("th", { className: "text-left py-2 px-2 text-dark-text/70 font-medium", children: "Symbol" }), _jsx("th", { className: "text-right py-2 px-2 text-dark-text/70 font-medium", children: "\u0394 (Delta)" }), _jsx("th", { className: "text-right py-2 px-2 text-dark-text/70 font-medium", children: "\u0393 (Gamma)" }), _jsx("th", { className: "text-right py-2 px-2 text-dark-text/70 font-medium", children: "\u0398 (Theta)" }), _jsx("th", { className: "text-right py-2 px-2 text-dark-text/70 font-medium", children: "\u03BD (Vega)" })] }) }), _jsx("tbody", { children: perps.greeks.map((greek, idx) => (_jsxs("tr", { className: "border-b border-dark-border/50 hover:bg-dark-bg/50", children: [_jsx("td", { className: "py-2 px-2 font-semibold text-dark-text", children: greek.symbol }), _jsxs("td", { className: `text-right py-2 px-2 font-mono ${greek.delta > 0 ? 'text-success' : 'text-danger'}`, children: [greek.delta > 0 ? '+' : '', greek.delta.toFixed(3)] }), _jsx("td", { className: `text-right py-2 px-2 font-mono ${greek.gamma > 0 ? 'text-accent' : 'text-dark-text/50'}`, children: greek.gamma.toFixed(4) }), _jsxs("td", { className: `text-right py-2 px-2 font-mono ${greek.theta < 0 ? 'text-danger' : 'text-success'}`, children: [greek.theta < 0 ? '−' : '+', Math.abs(greek.theta).toFixed(4)] }), _jsxs("td", { className: `text-right py-2 px-2 font-mono ${greek.vega > 0 ? 'text-warn' : 'text-dark-text/50'}`, children: [greek.vega > 0 ? '+' : '', greek.vega.toFixed(4)] })] }, idx))) })] }) }), _jsxs("div", { className: "text-xs text-dark-text/50 mt-3 space-y-1", children: [_jsx("div", { children: "\u0394: Sensitivity to underlying price" }), _jsx("div", { children: "\u0393: Rate of change of delta" }), _jsx("div", { children: "\u0398: Daily decay (theta bleed)" }), _jsx("div", { children: "\u03BD: Sensitivity to volatility" })] })] }) }));
};
