import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useStore } from '../../lib/store';
export const RyTopBar = () => {
    const [searchOpen, setSearchOpen] = useState(false);
    const [product, setProduct] = useState('Spot');
    const { markets, safety } = useStore();
    const products = ['Spot', 'Perps', 'SSP', 'Vaults'];
    const tokens = Object.keys(markets.cards || {});
    return (_jsxs("header", { className: "bg-panel border-b border-border p-4 flex justify-between items-center sticky top-0 z-40", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "text-xl font-bold text-accent", children: "RYZE-UP" }), _jsx("select", { value: product, onChange: (e) => setProduct(e.target.value), className: "px-2 py-1 rounded bg-subtext/10 text-sm", children: products.map(p => _jsx("option", { children: p }, p)) })] }), _jsxs("div", { className: "relative flex-1 max-w-xs mx-8", children: [_jsx("button", { onClick: () => setSearchOpen(!searchOpen), className: "w-full px-3 py-2 rounded bg-subtext/10 text-sm text-left text-subtext", children: "\u2318K Search..." }), searchOpen && (_jsxs("div", { className: "absolute top-full left-0 right-0 mt-1 bg-panel border border-border rounded shadow-lg z-50", children: [_jsx("input", { autoFocus: true, placeholder: "Search symbols...", className: "w-full px-3 py-2 border-b border-border outline-none" }), _jsx("div", { className: "max-h-48 overflow-y-auto", children: tokens.slice(0, 10).map(sym => (_jsxs("div", { className: "px-3 py-2 hover:bg-subtext/10 cursor-pointer text-sm flex justify-between", children: [_jsx("span", { children: sym }), _jsxs("span", { className: "text-subtext", children: ["$", markets.cards[sym]?.price.toFixed(2)] })] }, sym))) })] }))] }), _jsxs("div", { className: "flex items-center space-x-4 text-sm", children: [_jsxs("span", { className: `flex items-center space-x-1 ${safety.matching ? 'text-success' : 'text-danger'}`, children: [_jsx("span", { className: "w-2 h-2 rounded-full", style: { backgroundColor: safety.matching ? 'var(--success)' : 'var(--danger)' } }), _jsx("span", { children: safety.matching ? 'Online' : 'Offline' })] }), _jsx("span", { children: "p50: 50\u03BCs" }), _jsx("span", { children: "p95: 120\u03BCs" }), _jsx("button", { className: "px-2 py-1 rounded bg-subtext/10", children: "Settings" })] })] }));
};
